List<Map<String, dynamic>> allceo = [
  {
    'lat' : "21.20413468383875",
    'log' : "72.83080241656441",
    'ceo' : "CEO",
    'cname': "Apple",
    'ceoname': "Tim Cook",
    'ceoimage': "assets/images/appleceo.jpeg",
    'image': "assets/images/applelogo.png",
    'desc':
        "Apple Inc. (Apple) designs, manufactures and markets smartphones, personal computers, tablets, wearables and accessories and sells a range of related services. The Company's products include iPhone, Mac, iPad, AirPods, Apple TV, Apple Watch, Beats products, HomePod, iPod touch and accessories.",
  },
  {
    'lat' : "30.268367454151917",
    'log' : "-97.74451287854453",
    'ceo' : "CEO",
    'cname': "Tesla",
    'ceoname': "Elon Musk",
    'ceoimage': "assets/images/teslaceo.jpeg",
    'image': "assets/images/teslalogo.png",
    'desc': "Tesla Inc (Tesla) is an automotive and energy company. It designs, develops, manufactures, sells, and leases electric vehicles and energy generation and storage systems. The company produces and sells the Model Y, Model 3, Model X, Model S, Cybertruck, Tesla Semi, and Tesla Roadster vehicles.=",
  },
  {
    'lat' : "37.22604431086152",
    'log' : "-122.20444299999178",
    'ceo' : "CEO",
    'cname': "Google",
    'ceoname': "Sundar Pichai",
    'ceoimage': "assets/images/googleceo.jpeg",
    'image': "assets/images/googlelogo.png",
    'desc': "What Does Google Mean? Google is an internet search engine. It uses a proprietary algorithm that's designed to retrieve and order search results to provide the most relevant and dependable sources of data possible.",
  },
  {
    'lat' : "44.52649369243661",
    'log' : "10.866494658872753",
    'ceo' : "CEO",
    'cname': "Ferrari",
    'ceoname': "Benedetto Vigna",
    'ceoimage': "assets/images/ferrariceo.jpeg",
    'image': "assets/images/ferrarilogo.png",
    'desc': "Ferraris are what dreams are made of. Fast, sexy, and highly exclusive, these Italian supercars push the boundaries of performance and cause a stir wherever they go. The sensually styled Roma coupe is the most accessible in terms of price, but even it is far too expensive for most people.",
  },
  {
    'lat' : "18.934935421093357",
    'log' : "72.82695286341811",
    'ceo' : "CEO",
    'cname': "Jio",
    'ceoname': "Akash Ambani ",
    'ceoimage': "assets/images/jioceo.jpeg",
    'image': "assets/images/jiologo.png",
    'desc': "Reliance Jio Infocomm Limited, doing business as Jio, is an Indian telecommunications company and a subsidiary of Jio Platforms, headquartered in Navi Mumbai, Maharashtra, India. It operates a national LTE network with coverage across all 22 telecom circles. Jio offers 4G and 4G+ services all over India and 5G service in many cities.",
  },
  {
    'lat' : "19.1097189390006",
    'log' : "72.8544192894208",
    'ceo' : "CEO",
    'cname': "TATA Motors",
    'ceoname': "Natarajan",
    'ceoimage': "assets/images/tataceo.jpeg",
    'image': "assets/images/tatalogo.png",
    'desc': "Tata Group, privately owned conglomerate of nearly 100 companies encompassing several primary business sectors: chemicals, consumer products, energy, engineering, information systems, materials, and services. Headquarters are in Mumbai. ",
  },
  {
    'lat' : "23.157781383660392",
    'log' : "72.55571354572793",
    'ceo' : "CEO",
    'cname': "Adani",
    'ceoname': "Karan Adani",
    'ceoimage': "assets/images/adaniceo.jpeg",
    'image': "assets/images/adanilogo.png",
    'desc': "Adani Group is a diversified organisation in India comprising 7 publicly traded companies. It has created a world class transport and utility infrastructure portfolio that has a pan-India presence. Adani Group is headquartered in Ahmedabad, in the state of Gujarat, India.",
  },
  {
    'lat' : "18.51353540175567",
    'log' : "73.6651240098835",
    'ceo' : "CEO",
    'cname': "Coco-Cola",
    'ceoname': "James",
    'ceoimage': "assets/images/colaceo.jpeg",
    'image': "assets/images/colalogo.png",
    'desc': "The Coca-Cola Company (NYSE: KO) is a total beverage company with products sold in more than 200 countries and territories. Our company's purpose is to refresh the world and make a difference. Our portfolio of brands includes Coca-Cola, Sprite, Fanta and other sparkling soft drinks.",
  },
];
